### ISSUE TITLE
Aria2无法创建指定目录下载失败

### ISSUE THREAD

**Issue by YodaYuuk1** [dawn-lc/user.js#39]
# **已自行解决，删除插件设置里面的默认的下载位置即可**

插件优化的建议：增加全选功能，一个一个点太累了

你好，我下载了批量下载iwara该插件，以及ariang。
我在ariang设置如图：
![65A360DE-8C7B-4EF0-A1F6-B11481024F8D](https://user-images.githubusercontent.com/56193605/181841113-6df37c72-7336-4f24-84d9-140abb5c1c43.png)
下载截图：
![1082E2D3-2B5C-4CB7-BC06-AD7AD8746774](https://user-images.githubusercontent.com/56193605/181841226-12e398c0-c926-4edb-9161-ec7e0d21f3cb.png)
插件设置如图，秘钥是我自己设置的，没有错误：
![E8BBFD93-5780-4205-AA71-BA8957FB673A](https://user-images.githubusercontent.com/56193605/181841292-f587b93b-e5fe-45ce-a28f-edd84887a124.png)

**### 在传输成功之后ariang开始下,提示无法创建指定目录，查了资料也不是特别懂，请问该怎么解决？**
<img width="723" alt="image" src="https://user-images.githubusercontent.com/56193605/181845301-76539b50-3ad6-457d-86fe-cc389aa2eef5.png">

操作系统：
mac os Monterey  12.3.1
MacBook Air (M1, 2020)

谷歌浏览器版本 ：103.0.5060.134（正式版本） (arm64)

**Comment by dawn-lc** [comment]
根据版本不同，需要正确配置可以由aria2访问并写入的目录，或留空使用aria2默认配置。

**Comment by YodaYuuk1** [comment]
> 根据不同的版本，需要正确配置可以由 aria2 访问并写入的目录，或留空使用 aria2 默认配置。

现在成功接入是没有问题了，就是速度一丁点都没有，最先开始用的时候没啥问题，满速下载，下了十个左右，后来就全0%0kb不动了，各种查资料搞了一个小时半终于成功开始下了三四部，下完又不动了。气得我去睡觉，醒来看记录，决定去睡觉的一个小时后开始下载又下完了，于是便继续下了七八部，现在又卡了，总感觉就像触发了什么一小时只能下载几个的规则。
我网络环境是在境外，自认为应该没有特大问题
请问该怎么解决？


<img width="954" alt="image" src="https://user-images.githubusercontent.com/56193605/181878227-c65114d9-e1cb-4f11-b7c7

![D40C40DE-FE6E-4CBD-B166-515714E0EED8](https://user-images.githubusercontent.com/56193605/181878363-775c3c6b-d2a0-4c51-a01c-cc06b4729e71.png)
-e54fa269b176.png">

![04A4BCE3-6612-42A4-98CC-86BC5F153358](https://user-images.githubusercontent.com/56193605/181878379-714178b0-2b24-46eb-9e4b-002c04b80190.png)


这个是网页下载的报错：

![56457661-848D-4363-BBFE-8FA64A621AA7](https://user-images.githubusercontent.com/56193605/181878297-6298fc5f-50c1-4cc0-986f-906d755a0913.png)

**Comment by YodaYuuk1** [comment]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/56193605/181878826-46715e29-e12c-4b5e-a7ca-23beb133d8f4.png">



又开始下载了，就很折磨

**Comment by dawn-lc** [comment]
你这个情况应该是遇到了连接数限制，请设置下载线程数为4线程，同时进行的任务数限制至5一下，即总线程数不超过20，每个任务不超过4个

**Comment by dawn-lc** [comment]
我使用16线程每任务成功复现了你问题。

**Comment by dawn-lc** [comment]
全选功能在作者主页可用

>

**Comment by YodaYuuk1** [comment]
> 你这个情况应该是遇到了连接数限制，请设置下载线程数为4线程，同时进行的任务数限制至5一下，即总线程数不超过20，每个任务不超过4个

好的，我已经把最大同时下载数4，但不明白你说的“下载线程数为4线程”，下载线程指的是“单服务器最大连接数（我这为16）“还是”单服务器连接数？“（我这为64）

**Comment by YodaYuuk1** [comment]
我目前把最大同时下载数修改为3，在http/ftp/sftp设置中把”单服务器最大连接数“修改成4（也换成过3），删除任务重新下载依旧是老样子，”单服务器连接数“我有保持在默认的64以及4之间也尝试过，依旧如此。

**Comment by dawn-lc** [comment]
![image](https://user-images.githubusercontent.com/30336566/182007211-d1434aba-a0c4-4888-bf49-8139fdb6a66e.png)

**Comment by YodaYuuk1** [comment]
经过一小段测试，似乎解决了。
感谢一直以来的帮助。
还有个小建议，不知道是否是我的问题，在视频播放的主页面，右侧的More from user以及More like this的视频无法点击，左右键都不行。

**Comment by dawn-lc** [comment]
![image](https://user-images.githubusercontent.com/30336566/182039461-c6719e9c-d1e5-465f-9c3a-5a4fac01a971.png)

**Comment by YodaYuuk1** [comment]
没错，只能双击点击下载而不能打开视频网页。

**Comment by a419416951** [comment]
![image](https://user-images.githubusercontent.com/55371090/212341532-c1d7fa34-0ba8-4934-8789-182f845dab20.png)
大佬请问这个是什么错误？也是下载速度为0
