### ISSUE TITLE
下载私有视频时报错，或许可以加个提示或者跳过这个视频

### ISSUE THREAD

**Issue by xuejianxianzun** [dawn-lc/user.js#47]
页面：https://ecchi.iwara.tv/users/%E5%BF%83%E5%AE%BF%E4%B8%89kuon/videos

脚本 @version           2.1.70
浏览器 Chrome 106

重现步骤：
1. 双击选中第一个视频（这个是私有视频，能看到封面但是点进去看不了）
2. 批量下载-下载所选
3. 控制台出现错误，下载无法开始

`Uncaught (in promise) TypeError: videoInfo.getName is not a function`

截图：
![20220929_190121](https://user-images.githubusercontent.com/17283977/193014752-f5534187-b8da-433c-9478-b98ad5daa1e4.png)

**Comment by dawn-lc** [comment]
已修复，请尽快更新

**Comment by dawn-lc** [comment]
事实上很早以前就加了私有视频提示，但是有bug触发不了，这回修了有问题直接回复我

**Comment by dawn-lc** [comment]
超过7天没有同样问题反馈, 视为已解决
