### ISSUE TITLE
请问文件名变量可否添加视频的发表日期？

### ISSUE THREAD

**Issue by xuejianxianzun** [dawn-lc/user.js#54]
现在的日期我试了，用的是当前时间。
例: %#Y#%-%#M#%-%#D#%_%#TITLE#%.MP4
结果: 2023-2-4_标题.MP4

下载下来无法起到让文件按文件名排序的效果，只能知道是哪一天下载的。
2023-2-4_蛇蛇的恋爱循环(里)
2023-2-4_绑起来炒鸭
2023-2-4_素裳的沙滩vlog

如果能使用视频的发表日期，就可以把它们按发布顺序排列了。

**Comment by dawn-lc** [comment]
功能已添加
