### ISSUE TITLE
初步支持新版本，请切换至dev分支体验

### ISSUE THREAD

**Issue by dawn-lc** [dawn-lc/user.js#57]
![image](https://user-images.githubusercontent.com/30336566/225598340-e745aa43-a13c-41e3-b94a-fc42960dd541.png)

**Comment by dawn-lc** [comment]
这api好爽啊, 不用自己解析了上传时间之类的了

**Comment by dawn-lc** [comment]
初步支持新版本请切换至dev分支体验

**Comment by dotaraku** [comment]
新版网页没有以前的插件ui，请问是要怎么操作才能显示？

**Comment by xuejianxianzun** [comment]
> 

更新脚本，新版脚本在页面右侧有个浮动块可以显示操作菜单。

**Comment by KONG424** [comment]
![image](https://user-images.githubusercontent.com/81810616/228798866-bad3fec0-76ac-4acc-b834-54bd02ffc69b.png)
这个标签含义怎么没了，已经忘了之前怎么设定的了

**Comment by dotaraku** [comment]
就很奇怪，我的aria收不到插件的推送

**Comment by dotaraku** [comment]
以前那个基本设置下面选项，然后拉到最下面有个单任务最大连接数要限制到32，你比我好多了，我现在插件都推送不进aira2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dawn-lc/user.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57)





 你好，我想问一下之前我好像也是直接选第二个就可以下载了，但现在没反应了。现在是要专门在弄个下载器吗？现在只有第三个可以下载，但不能自定义名字。第一个Aria2我弄了 
 ，但一直0%没有速度，今天我弄了很久，还是不懂，想问一下怎么可以使用 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "dawn-lc/user.js"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年3月31日(星期五) 晚上11:18 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57) 
 
 
 
 
 
  应该是作者，名称，iwara的视频id  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "dawn-lc/user.js"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年3月30日(星期四) 下午5:52  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57)  
   
   
   
   
   
     
   
   这个标签含义怎么没了，已经忘了之前怎么设定的了

**Comment by dawn-lc** [comment]
测试推送至aria2是没有问题的, 请填写完整的aria2 rpc地址例如 :  http://127.0.0.1:6800/jsonrpc

**Comment by KONG424** [comment]
我的rpc地址是：http://localhost:6800/jsonrpc，还行不行是那哪里设置错了吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dawn-lc/user.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57)





 
测试推送至aria2是没有问题的, 请填写完整的aria2 rpc地址例如 :  http://127.0.0.1:6800/jsonrpc

**Comment by dawn-lc** [comment]
> 我的rpc地址是：http://localhost:6800/jsonrpc，还行不行是那哪里设置错了吗？
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "dawn-lc/user.js"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2023年4月1日(星期六) 下午2:16
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57)
> 
> 
> 
> 
> 
>  
> 测试推送至aria2是没有问题的, 请填写完整的aria2 rpc地址例如 :  http://127.0.0.1:6800/jsonrpc
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

脚本是以post的方式推送任务的，在尝试推送任务前，如果你的aria2rpc地址与这个页面所属的域不同，会触发跨域安全策略，会弹窗一个页面询问你是否同意脚本向你的aria2rpc地址所处的域发送请求，如果你在该页面未点击同意则有可能会出现无法推送任务到aria2的情况

**Comment by dotaraku** [comment]
可能测试环境不太一样，aira2推送不管成没成功都没弹出过确认弹窗。

旧版网页的插件使用倒是没什么问题，就很奇怪

**Comment by dawn-lc** [comment]
> 

请打开开发者工具并录制你的操作画面, 我需要更多信息

**Comment by dawn-lc** [comment]
> 我的rpc地址是：http://localhost:6800/jsonrpc，还行不行是那哪里设置错了吗？

@KONG424 我需要更多的信息才能判断你遇到了什么问题

**Comment by KONG424** [comment]
视频在附件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dawn-lc/user.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57)





   
请打开开发者工具并录制你的操作画面, 我需要更多信息
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Desktop 2023.04.02 - 18.32.38.01.mp4 (173.08M, 2023年05月02日 18:36 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=6c36373418894acc3f96c055473956164d420e50500f5100185407565614535c02011a03525f57140d070f0c040d570e5350550c611d647d50455c400e49440b0504041a510d4a0907161a1450014a0a0718040c4f095517584603345c&code=5674a9d9

**Comment by dotaraku** [comment]
![image](https://user-images.githubusercontent.com/25920271/229349332-ebd2f29c-31c1-413f-9d75-7fd4c10ae01a.png)

这个确实有用，是我自己操作失误，不好意思，重置油猴重装脚本，按图选择允许能推送到aria2了

**Comment by dotaraku** [comment]
> 视频附件
> [……](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dawn-lc/user.js" ***@***.***&gt;; 发送时间:&nbsp;2023年4月2日(星期天) 下午5:39 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57) 请打开开发者工具并录制你的操作画面, 我需要更多信息 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt; 从QQ邮箱发来的超大附件 Desktop 2023.04.02 - 18.32.38.01.mp4 (173.08M, 2023年05月02日 18:36 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=6c36373418894acc3f96c055473956164d420e50500f5100185407565614535c02011a03525f57140d070f0c040d570e5350550c611d647d50455c400e49440b0504041a510d4a0907161a1450014a0a0718040c4f095517584603345c&code=5674a9d9

过来人经验，你的梯子试一下全局TUN模式，光http模式我之前也不能下载

**Comment by dawn-lc** [comment]
@KONG424 
请检查你的aria2是否处于可以访问iwara的环境下. 大概率是这个问题
还有一种可能, 你需要使用Tampermonkey Beta注入本脚本以及登录了i站账号, 有一些视频i站会校验cookies以及authorization

**Comment by dotaraku** [comment]
询问下，现在路径变量 %#AUTHOR#% (作者) 获取的是视频主的账号id？不再是昵称了？
例如：
[三仁月饼](https://www.iwara.tv/profile/user223528)
@user223528

获取的是user223528，旧版获取的是昵称id？
现在归类跟以前的有点冲突了

**Comment by dawn-lc** [comment]
@dotaraku 昵称有可能包含特殊字符以及操作系统不支持的unicode字符, 安全起见不在获取昵称, 脚本VideoInfo类型下添加了一个Alias字段存储昵称, 有需要可以手动更改

**Comment by dawn-lc** [comment]
> 还有就是下载资源发现链接就不推送，弹窗说高清资源，但是很多是作者的赞助网址，有链接的反而不能自动下载来？

新版本添加了检查开关, 可以手动关闭检查

**Comment by KONG424** [comment]
我更新插件并关闭高画质检测了，但现在三个下载方式都不行...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dawn-lc/user.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57)





  
还有就是下载资源发现链接就不推送，弹窗说高清资源，但是很多是作者的赞助网址，有链接的反而不能自动下载来？
  
新版本添加了检查开关, 可以手动关闭检查

**Comment by dawn-lc** [comment]
@KONG424 三个都不行我怀疑是配置问题, 重装脚本试试

**Comment by KONG424** [comment]
现在能推送，但下载没有还是速度...






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dawn-lc/user.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 晚上9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57)





 
@KONG424 三个都不行我怀疑是配置问题, 重装脚本试试

**Comment by dotaraku** [comment]
> @dotaraku 昵称有可能包含特殊字符以及操作系统不支持的unicode字符, 安全起见不在获取昵称, 脚本VideoInfo类型下添加了一个Alias字段存储昵称, 有需要可以手动更改 Iwaradownlaoder 在下载时会将昵称存储到数据库中 供播放列表功能使用

以后条件允许的情况下还是希望能更新方便识别的方法

**Comment by dotaraku** [comment]
> 现在能推送，但下载没有还是速度...
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dawn-lc/user.js" ***@***.***&gt;; 发送时间:&nbsp;2023年4月2日(星期天) 晚上9:26 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [dawn-lc/user.js] 初步支持新版本，请切换至dev分支体验 (Issue #57) @KONG424 三个都不行我怀疑是配置问题, 重装脚本试试 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

你试过更换梯子，使用TUN全局模式了么？还有http下载最大连接数要改

**Comment by YodaYuuk1** [comment]
操作系统：OS 13.2.1 (22D68)
浏览器：CHROME  111.0.5563.146（正式版本） (arm64)
下载软件：ariang Native 1.2.4

报错：
Aria2 RPC 连接测试
无法保存配置, 请检查配置是否正确。
错误信息：{"responseText":"","response":null,"readyState":4,"responseHeaders":"","status":0,"statusText":"","error":"Invalid scheme","DONE":4,"HEADERS_RECEIVED":2,"LOADING":3,"OPENED":1,"UNSENT":0,"RESPONSE_TYPE_TEXT":"text","RESPONSE_TYPE_ARRAYBUFFER":"arraybuffer","RESPONSE_TYPE_BLOB":"blob","RESPONSE_TYPE_DOCUMENT":"doc



假想原因：
1：在设置中“下载到”一栏中，默认的应该类似于  iwara/%#TITLE#%[%#ID#%]  这样的格式，因为上个版本的遗留习惯，我直接删掉了并修改成了 /Users/yodayuuki/Downloads，如果aria2地址设置没出错的话，可能是这块导致的报错，不过种种迹象表明应该不是。
2：aria native中设置出错，与前缀https和ws有关？

ps：在aria native中 目前只修改了单任务连接数，从64修改至32

自我尝试过的操作：
1：重复卸载插件，使用默认“下载至”目录，可能是我操作有误，怎么样都是我之前遗留的路径，留空也是如此。
2：再次确实是否允许插件访问跨源资源权限。
3：肉身在外国，应该与网络问题无关。

参考图：
https://img.chkaja.com/964b48b0b34a955a.jpg

https://img.chkaja.com/c156d66688828503.jpg

https://img.chkaja.com/b16aa760d5ea4db7.jpg

**Comment by dawn-lc** [comment]
@YodaYuuk1 看了报错信息，是脚本没法连接到aria2rpc 请尝试在其他使用aria2rpc的软件中使用相同的rpc地址和token连接你的aria2。
若在其他使用aria2rpc的软件中使用相同的rpc地址和token连接你的aria2可以正常使用，请加我QQ我远程康康啥问题

**Comment by YodaYuuk1** [comment]
这个是视频流程，我已经上传至托管网站了。
不知道操作有没有失误，总之能成功添加任务到浏览器插件和软件，尽管没有速度。
因为iwara目前在维护，没法再进行测试...
os真麻烦

https://pixeldrain.com/u/ro8Vmsj7

**Comment by dawn-lc** [comment]
@YodaYuuk1 我想我知道问题原因了
脚本目前仅支持通过http或https调用rpc
不支持ws或wss

**Comment by YodaYuuk1** [comment]
这样啊，刚刚只能看到502，现在iwara已经可以进去了。

那之后会支持ws和wss吗，只用ws系我能连接上，我用http系会显示未连接，没有什么计算机基础所以完全不知道咋弄，打算明天弄了

**Comment by dawn-lc** [comment]
> 这样啊，刚刚只能看到502，现在iwara已经可以进去了。
> 
> 那之后会支持ws和wss吗，只用ws系我能连接上，我用http系会显示未连接，没有什么计算机基础所以完全不知道咋弄，打算明天弄了

由于浏览器跨域限制，以及脚本管理器尚未实现跨域ws或wss方法，暂无计划支持。
另外aria2rpc不分协议，启动后ws和http同时可用

**Comment by YodaYuuk1** [comment]
我也是那么想的，之前就不行，你这么一说我今早试了试又突然行了...
总之，连接是连接上了，也能保存设置没有报错，但无法推送到aria，是否是我在“下载至”框留空的原因？默认为？

**Comment by dawn-lc** [comment]
> > @dotaraku 昵称有可能包含特殊字符以及操作系统不支持的unicode字符, 安全起见不在获取昵称, 脚本VideoInfo类型下添加了一个Alias字段存储昵称, 有需要可以手动更改 Iwaradownlaoder 在下载时会将昵称存储到数据库中 供播放列表功能使用
> 
> 以后条件允许的情况下还是希望能更新方便识别的方法

已加入作者昵称变量，请更新至最新版本。
