### ISSUE TITLE
请问新版脚本在哪里修改文件名规则？

### ISSUE THREAD

**Issue by xuejianxianzun** [dawn-lc/user.js#68]
虽然第一次运行时会提示命名变量，但是没找到在哪里修改。
右侧的“打开设置”按钮只能选择下载方式。

**Comment by dawn-lc** [comment]
直接输入整个路径即可例如:
![image](https://user-images.githubusercontent.com/30336566/228617685-da932a9e-4b3f-45a9-bb18-eebbe8ac4b62.png)

**Comment by dawn-lc** [comment]
> 我用浏览器自带下载（选的 Other）而非 aria2，是不是就不能设置文件名了…… 另外 IwaraDownloader 是什么软件呀 ![image](https://user-images.githubusercontent.com/17283977/228618410-bb1a0d52-7b7f-4f17-a851-55f121c5040f.png)

是的, 目前优先适配新版i站, 其次是aria2, 至于说IwaraDownloader是我自己写的下载器, 调用aria2没法保存tag和评论信息, 只能自己实现了 目前还在开发中

**Comment by dawn-lc** [comment]
![image](https://user-images.githubusercontent.com/30336566/228620762-bacad078-bc7b-4928-8dca-3f1159131468.png)
![image](https://user-images.githubusercontent.com/30336566/228620854-d458ec2b-1ec3-4e8d-bf9e-8f8ec6b9fc7e.png)

**Comment by xuejianxianzun** [comment]
厉害捏！

**Comment by xuejianxianzun** [comment]
那等于是做了一个视频管理软件了吧（

我用 Aria2 可以下载并且重命名了（我是调用的 Motrix），之前习惯用浏览器自带的，反正 iwara 的文件体积都不大。
![image](https://user-images.githubusercontent.com/17283977/228622183-81adceeb-dad9-4448-90b9-b88dadb1a8fa.png)

**Comment by xuejianxianzun** [comment]
加油捏！

**Comment by dawn-lc** [comment]
chromium和Firefox 在执行event.stopPropagation()之后的行为是不一致的.
你有没有遇到过这个问题?
目前因为这个问题脚本没法兼容火狐

**Comment by xuejianxianzun** [comment]
不清楚，我没用火狐
