### ISSUE TITLE
点击下载所选，出现报错导致无法下载

### ISSUE THREAD

**Issue by xuejianxianzun** [dawn-lc/user.js#69]
https://www.iwara.tv/profile/user1234775/videos
选择右下角的视频（其他视频也一样），点击下载所选，报错：

![image](https://user-images.githubusercontent.com/17283977/228458909-f28eaf5d-e773-427a-8487-5d26723011fd.png)

![image](https://user-images.githubusercontent.com/17283977/228458976-7b8d60d2-3a43-49ec-9db3-b918038ac186.png)

```
undefined[bgambuon74u1m6zn8] TypeError: Cannot read properties of undefined (reading 'map')

init @ userscript.html?name=Iwara%2520Download%2520Tool.user.js&id=faa37ea6-24c1-41d0-8961-02834287db24:494
await in init（异步）
analyzeDownloadTask @ userscript.html?name=Iwara%2520Download%2520Tool.user.js&id=faa37ea6-24c1-41d0-8961-02834287db24:746
await in analyzeDownloadTask（异步）
click @ userscript.html?name=Iwara%2520Download%2520Tool.user.js&id=faa37ea6-24c1-41d0-8961-02834287db24:1146
```

**Comment by dawn-lc** [comment]
新版本应该修复了, 如果更新了还是存在同样的错误,请使用支持GM_cookie方法的脚本加载器
