### ISSUE TITLE
bug反馈 _3.1.12版本，点击开关选择无反应 ，选择框出不来

### ISSUE THREAD

**Issue by HANA00** [dawn-lc/user.js#93]

**Comment by YodaYuuk1** [comment]
me 2

**Comment by dawn-lc** [comment]
请提供更多信息

**Comment by YodaYuuk1** [comment]
更新插件之后 os 系统 Chrome 浏览器 点击开关选择后没有任何反应（无框框）
手动下载没有问题
<img width="2301" alt="image" src="https://user-images.githubusercontent.com/56193605/235294134-809e503f-eed2-488d-97c7-1776046f0fca.png">

**Comment by dawn-lc** [comment]
请提供控制台输出

**Comment by YodaYuuk1** [comment]
控制台输出是？

**Comment by dawn-lc** [comment]
**问题描述**
清晰简明的描述该问题。

**重现步骤**
重现此问题的步骤：
1. 进入“...”
2. 点击“...”
3. 遇到错误

**期望行为**
对您期望发生的结果进行清晰简明的描述。

**截图**
如果条件允许，添加截图以帮助解释您的遇到的问题。

**报错信息**
（请填写以下信息）
 - [例如 Aria2 RPC 连接测试 无法保存配置, 请检查配置是否正确。]

**环境信息**
（请填写以下信息）
 - 操作系统：[例如 Windows 10]
 - 浏览器：[例如 Chrome]
 - 浏览器版本：[例如 111.0.5563.146]
 - 脚本管理器：[例如 Tampermonkey Beta]
 - 脚本版本：[例如 3.1.1]
 - 下载模式：[例如 Aria2]
 - 其他

**其他信息**
在此处添加有关问题的任何其他上下文信息。

**Comment by dawn-lc** [comment]
> 控制台输出是？

打开浏览器开发者工具，点击控制台选项卡

**Comment by YodaYuuk1** [comment]
<img width="2104" alt="image" src="https://user-images.githubusercontent.com/56193605/235295256-518a55c1-9f82-477c-94e5-6caca74df09f.png">

不知道是否为这个？

Sentry enabled.
main.e2a734920272a1c3a978.js:2 Build 3.0.30 at Sat, 08 Apr 2023 01:47:32 GMT
userscript.html?name=Iwara%2520Enhancement.user.js&id=0048f147-f463-446d-a32d-d228092d3bb8:21525 You are running a development build of Vue.
Make sure to use the production build (*.prod.js) when deploying for production.
userscript.html?name=Iwara%2520Enhancement.user.js&id=0048f147-f463-446d-a32d-d228092d3bb8:29479 You are running a development build of vue-i18n.
Make sure to use the production build (*.prod.js) when deploying for production.
userscript.html?name=Iwara%2520Enhancement.user.js&id=0048f147-f463-446d-a32d-d228092d3bb8:32269 [Iwara Enhancement] Start observing pages.
main.e2a734920272a1c3a978.js:2 Service worker registered.
userscript.html?name=Iwara%2520Enhancement.user.js&id=0048f147-f463-446d-a32d-d228092d3bb8:33172 [Iwara Enhancement] Settings view initialized
DevTools failed to load source map: Could not load content for https://www.iwara.tv/chunk-9249.0f9a1f09bdeb85c8811a.js.map: HTTP 错误：状态代码 403，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.iwara.tv/chunk-341.22437cb29e60a4b76500.js.map: HTTP 错误：状态代码 403，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.iwara.tv/main.e2a734920272a1c3a978.js.map: HTTP 错误：状态代码 403，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.iwara.tv/chunk-6496.cec6e7894b8d9f456244.js.map: HTTP 错误：状态代码 403，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.iwara.tv/chunk-5039.0fd6b09cb0a2327cf8a2.js.map: HTTP 错误：状态代码 403，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.iwara.tv/chunk-4437.399ed2aaf78cd95cdce0.js.map: HTTP 错误：状态代码 403，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.iwara.tv/chunk-4330.1a5d7985aa5e41dab54e.js.map: HTTP 错误：状态代码 403，net::ERR_HTTP_RESPONSE_CODE_FAILURE
picture-789944-1562678432.jpg:1     GET https://i.iwara.tv/image/avatar/8e7e851f-bd7a-4699-be22-199b547ff9e5/picture-789944-1562678432.jpg 404

**Comment by dawn-lc** [comment]
是的，但是我没有在输出中看到您的操作，您需要先按照您预想的方式执行操作后我才能在控制台输出中看到有用的信息

**Comment by YodaYuuk1** [comment]
现在应该对了。

main.e2a734920272a1c3a978.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'brands')
    at HTMLLIElement.click (userscript.html?name=Iwara%2520Download%2520Tool.user.js&id=b22ba008-2fbc-4b26-bc44-c09d1e6d35fd:1482:79)
    at HTMLLIElement.r (main.e2a734920272a1c3a978.js:2:977154)
click @ userscript.html?name=Iwara%2520Download%2520Tool.user.js&id=b22ba008-2fbc-4b26-bc44-c09d1e6d35fd:1482
r @ main.e2a734920272a1c3a978.js:2


<img width="572" alt="image" src="https://user-images.githubusercontent.com/56193605/235295443-6f5b3b40-3f51-4ae2-b7fb-b0bc1c4f7ba5.png">

**Comment by dawn-lc** [comment]
请点击
![image](https://user-images.githubusercontent.com/30336566/235295491-f88260b6-6dd4-49d1-86ee-e3df35f8d43b.png)

**Comment by dawn-lc** [comment]
然后截图全屏

**Comment by YodaYuuk1** [comment]
<img width="2307" alt="image" src="https://user-images.githubusercontent.com/56193605/235295593-bae2046f-41d5-4536-b176-eaf83490531d.png">

在我点进去之后，这块代码会闪一下（颜色为绿色，我标蓝的地方）

**Comment by dawn-lc** [comment]
好的已经找到问题原因了，正在修复

**Comment by YodaYuuk1** [comment]
ok，感谢您的辛苦工作，给我们带来方便的下载插件。
