### ISSUE TITLE
Browser下载无反应

### ISSUE THREAD

**Issue by z78966789** [dawn-lc/user.js#97]
选择后点击下载所选控制台截图
![image](https://user-images.githubusercontent.com/111133655/235512721-074663e3-2d6f-471b-8292-a571f255fb86.png)

**环境信息**
 - 操作系统：Windows 10
 - 浏览器：Chrome
 - 浏览器版本：112.0.5615.138（正式版本） （64 位）
 - 脚本管理器：Tampermonkey Beta 版本4.19.6182
 - 脚本版本：3.1.30
 - 下载模式：Browser

**Comment by dawn-lc** [comment]
请补充出现此情况的网址

**Comment by dawn-lc** [comment]
已修复，请及时更新脚本
